# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='When this item was last modified')),
                ('status', models.CharField(choices=[(b'Q', b'Queued'), (b'P', b'Playing'), (b'C', b'Complete')], default=b'Q', help_text=b'Whether the request is queued, playing or complete', max_length=1)),
                ('played_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='requests_request_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='requests_request_modifications', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(help_text=b'The track that has been requested', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tracks.Track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='When this item was last modified')),
                ('score', models.IntegerField(help_text=b'The score attributed to this vote')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='requests_vote_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='requests_vote_modifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(help_text=b'The request that was voted on', on_delete=django.db.models.deletion.CASCADE, to='requests.Request')),
                ('track', models.ForeignKey(help_text=b'The track being voted on', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tracks.Track')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
